### ISSUE TITLE
Cannot Make New Profile

### ISSUE THREAD

**Issue by oxocutable** [omen0x8/BetterDiscord#3]
Installed, Activated, Nothing.
Rebooted, Nothing.
Deleted, Reinstalled, Rebooted, Nothing.

I am assuming that I'm either doing something wrong or there is a mod/keybind conflict.
How would I go about repairing this?
Currently Alt+<key> types Unicode symbols.

Upon examination, I have no mods currently adding a keybind that includes Alt+ any of the numpad keys.
I would like to move the key, but do not know which part of the JS to modify to do so.

**Comment by blobbyblo** [comment]
I currently don't have a menu or visual settings area where you can modify the keybind yourself, but if you want to replace Alt then you can change the keymap code [from here](https://github.com/omen0x8/BetterDiscord/blob/5d84b07a661bda4d179ae50cb2666ffc41411882/Plugins/MultiAccounts/MultiAccounts.plugin.js#L106).

It should be Alt+NumberRow not NumberPad for the numbers.
